AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Description: "Bucket to store source code for instance-bleeper"
    Type: String

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
